<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\jerza\OneDrive\Pulpit\projects\threlte-fps-example\static\models\5.56x45mm_bullet.glb --root /models/ --types --printwidth 120 --precision 2
Author: RoleWeird (https://sketchfab.com/ROLEW)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/556x45mm-bullet-711aa46d883e40e28de14a0e10cc8863
Title: 5.56x45mm Bullet
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Casing_low_556Bullet_0: THREE.Mesh
      Bullet_low_556Bullet_0: THREE.Mesh
    }
    materials: {
      ['5.56Bullet']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/5.56x45mm_bullet.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Casing_low_556Bullet_0.geometry}
      material={gltf.materials['5.56Bullet']}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Bullet_low_556Bullet_0.geometry}
      material={gltf.materials['5.56Bullet']}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
