<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\jerza\OneDrive\Pulpit\projects\threlte-fps-example\static\models\scene.gltf --root /models/ --types --printwidth 120 --precision 2
Author: DJMaesen (https://sketchfab.com/bumstrum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/level-blockout-24b39d9beef54166a14e6f2542d01def
Title: level blockout
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	import { AutoColliders, Collider, Debug, World } from '@threlte/rapier';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			terrain1_terrain1_0: THREE.Mesh;
		};
		materials: {
			terrain1: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/level.gltf');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<AutoColliders shape="trimesh">
			<T.Group scale={0.002} position={[-20, 0, 5]}>
				<T.Mesh
					geometry={gltf.nodes.terrain1_terrain1_0.geometry}
					material={gltf.materials.terrain1}
				/>
			</T.Group>
		</AutoColliders>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
