<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\jerza\OneDrive\Pulpit\projects\threlte-fps-example\static\models\scene.gltf --root /models/ --types --printwidth 120 --precision 2
Author: BillyTheKid (https://sketchfab.com/FGmodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m4a1-with-hands-and-animations-79524d1b74e24962979127cbb5c0b55b
Title: M4A1 With Hands And Animations
-->

<script lang="ts">
	import * as THREE from 'three';
	import { DoubleSide, Group } from 'three';
	import {
		T,
		type Props,
		type Events,
		type Slots,
		forwardEventHandlers,
		useFrame
	} from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	type $$Props = Props<THREE.Group> & {
		startPosition: THREE.Vector3;
		endPosition: THREE.Vector3;
		shooting: boolean;
	};
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();
	export let shooting = false;

	type ActionName =
		| 'h2_skeleton|draw'
		| 'h2_skeleton|draw2'
		| 'h2_skeleton|fire1'
		| 'h2_skeleton|fire11'
		| 'h2_skeleton|fire2'
		| 'h2_skeleton|fire3'
		| 'h2_skeleton|fire33'
		| 'h2_skeleton|idle'
		| 'h2_skeleton|idle2'
		| 'h2_skeleton|reload'
		| 'h2_skeleton|reload2'
		| 'h2_skeleton|ss'
		| 'h2_skeleton|ss2';
	type GLTFResult = {
		nodes: {
			Object_10: THREE.SkinnedMesh;
			Object_11: THREE.SkinnedMesh;
			Object_12: THREE.SkinnedMesh;
			Object_13: THREE.SkinnedMesh;
			Object_15: THREE.SkinnedMesh;
			Object_16: THREE.SkinnedMesh;
			Object_17: THREE.SkinnedMesh;
			Object_18: THREE.SkinnedMesh;
			Object_19: THREE.SkinnedMesh;
			Object_20: THREE.SkinnedMesh;
			Object_21: THREE.SkinnedMesh;
			Object_22: THREE.SkinnedMesh;
			_rootJoint: THREE.Bone;
		};
		materials: {
			sleeve_col: THREE.MeshStandardMaterial;
			glove_col: THREE.MeshStandardMaterial;
			alpha_col: THREE.MeshStandardMaterial;
			digit_anim: THREE.MeshStandardMaterial;
			lense_col: THREE.MeshStandardMaterial;
			eotech_col: THREE.MeshStandardMaterial;
			magnifier_col: THREE.MeshStandardMaterial;
			lens_col: THREE.MeshStandardMaterial;
			m4_col: THREE.MeshStandardMaterial;
			sm_col: THREE.MeshStandardMaterial;
			foregrip_col: THREE.MeshStandardMaterial;
			suppressor_col: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/m4.gltf');
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();

	let scale = 0.01;
	$: $actions['h2_skeleton|idle']?.play();

	const cg = new THREE.SphereGeometry(0.1, 5, 5);
	const cm = new THREE.MeshStandardMaterial({ color: 'red', wireframe: true });

	const start = new THREE.Mesh(cg, cm);
	const end = new THREE.Mesh(cg, cm);

	let gunRef: any;

	$: {
		if (gunRef) {
			const bone = gunRef.skeleton.getBoneByName('tag_weapon_04');

			const zOffset = 2.6;
			start.position.x = 25;
			start.position.z = zOffset;
			end.position.x = 4;
			end.position.z = zOffset;

			bone.add(start);
			bone.add(end);
		}
	}

	const shootAnimation = (shooting: boolean) => {
		console.log({ shooting });
		if (shooting) {
			$actions['h2_skeleton|fire1']?.reset();
			$actions['h2_skeleton|fire1']?.setLoop(THREE.LoopRepeat, 1).play();
		} else {
			$actions['h2_skeleton|idle']?.play();
		}
	};

	$: shootAnimation(shooting);

	export let startPosition = new THREE.Vector3();
	export let endPosition = new THREE.Vector3();

	useFrame(() => {
		start.getWorldPosition(startPosition);
		end.getWorldPosition(endPosition);
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Sketchfab_Scene" frustumCulled={false}>
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} frustumCulled={false}>
				<T.Group
					name="ab25487b58b043d09a956bcac5cbf842fbx"
					rotation={[Math.PI / 2, 0, 0]}
					{scale}
					frustumCulled={false}
				>
					<T.Group name="Object_2" frustumCulled={false}>
						<T.Group name="RootNode">
							<T.Group name="h2" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
							<T.Group name="m4a1" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
							<T.Group name="h2_skeleton" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
								<T.Group name="Object_7">
									<T is={gltf.nodes._rootJoint} />
									<T.Group name="Object_9" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
									<T.Group name="Object_14" rotation={[-Math.PI / 2, 0, 0]} scale={100} />

									<T.SkinnedMesh
										name="Arms"
										geometry={gltf.nodes.Object_10.geometry}
										material={gltf.materials.sleeve_col}
										skeleton={gltf.nodes.Object_10.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="Hands"
										geometry={gltf.nodes.Object_11.geometry}
										material={gltf.materials.glove_col}
										skeleton={gltf.nodes.Object_11.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="Watch"
										geometry={gltf.nodes.Object_12.geometry}
										material={gltf.materials.alpha_col}
										skeleton={gltf.nodes.Object_12.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="Object_13"
										geometry={gltf.nodes.Object_13.geometry}
										material={gltf.materials.digit_anim}
										skeleton={gltf.nodes.Object_13.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="Object_15"
										geometry={gltf.nodes.Object_15.geometry}
										material={gltf.materials.lense_col}
										skeleton={gltf.nodes.Object_15.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="holo"
										geometry={gltf.nodes.Object_16.geometry}
										material={gltf.materials.eotech_col}
										skeleton={gltf.nodes.Object_16.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="scope_2x"
										geometry={gltf.nodes.Object_17.geometry}
										material={gltf.materials.magnifier_col}
										skeleton={gltf.nodes.Object_17.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="viewer_2x"
										geometry={gltf.nodes.Object_18.geometry}
										material={gltf.materials.lens_col}
										skeleton={gltf.nodes.Object_18.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="gun"
										geometry={gltf.nodes.Object_19.geometry}
										material={gltf.materials.m4_col}
										skeleton={gltf.nodes.Object_19.skeleton}
										frustumCulled={false}
										bind:ref={gunRef}
									/>
									<T.SkinnedMesh
										name="charging_handle"
										geometry={gltf.nodes.Object_20.geometry}
										material={gltf.materials.sm_col}
										skeleton={gltf.nodes.Object_20.skeleton}
										frustumCulled={false}
									/>
									<T.SkinnedMesh
										name="Object_21"
										geometry={gltf.nodes.Object_21.geometry}
										material={gltf.materials.foregrip_col}
										skeleton={gltf.nodes.Object_21.skeleton}
										frustumCulled={false}
									/>
									<!-- <T.SkinnedMesh
										name="Silencer"
										geometry={gltf.nodes.Object_22.geometry}
										material={gltf.materials.suppressor_col}
										skeleton={gltf.nodes.Object_22.skeleton}
										frustumCulled={false}
									/> -->
								</T.Group>
							</T.Group>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
